"""CSV export endpoint tests (PLAN.md §5, S5).

Everything runs offline through FastAPI's TestClient against a throwaway
database under pytest's ``tmp_path``; uploaded "PDFs" are generated byte
strings. Expected rows are derived from the *same* repository functions the
endpoints use (no re-implemented filtering logic), so these tests prove the
exports match the dashboard slice and the database exactly. The live
DATA_DIR is never touched (§7).
"""

import csv
import io
import re
from datetime import timedelta

import pytest
from fastapi.testclient import TestClient

from app import config, db, repo
from app.db import open_session
from app.main import create_app
from app.models import utc_now


@pytest.fixture()
def client(tmp_path, monkeypatch):
    """An app wired to a fresh temp DATA_DIR (database + upload files)."""
    data_dir = tmp_path / "data"
    # config reads it at call time for uploads; db binds its own copy and the
    # lazily-created engine/session factory must be dropped so lifespan's
    # init_db() rebuilds them against this test's temp dir.
    monkeypatch.setattr(config, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "_default_engine", None)
    monkeypatch.setattr(db, "_default_factory", None)

    with TestClient(create_app()) as test_client:
        yield test_client

    # Don't let later tests or a re-imported module reuse this temp database.
    db._default_engine = None
    db._default_factory = None


APP_COLUMNS = [
    "id",
    "company",
    "job_title",
    "reference_number",
    "applied_on",
    "status",
    "job_posting_url",
    "notes",
    "resume_filename",
    "application_filename",
    "created_at",
    "updated_at",
]

EVENT_COLUMNS = ["application_id", "company", "from_status", "to_status", "changed_at"]


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _pdf(name: str, tag: bytes) -> tuple[str, bytes, str]:
    """A generated PDF-shaped payload for multipart uploads (offline §7)."""
    return name, b"%PDF-1.7\n% " + tag + b"\n%%EOF", "application/pdf"


def _seed(client):
    """Four applications across two companies/dates with a known event history.

    Returns ``R`` — the UTC "today" all applied dates are offset from:

    * A1 Acme Corp / Backend Engineer, R-10, received, both PDFs (distinct
      original filenames, notes containing CSV-hostile characters).
    * A2 Acme Corp / SRE, R-30, then changed to rejected. No PDFs.
    * B1 Globex / Data Analyst, R-4, then changed to offer. Application PDF only.
    * C1 Initech / Frontend Dev, R-2, still received. No PDFs.
    """
    R = utc_now().date()

    def at(days_ago: int) -> str:
        return (R - timedelta(days=days_ago)).isoformat()

    a1 = client.post("/applications/new", data={
        "company": "Acme Corp",
        "job_title": "Backend Engineer",
        "applied_on": at(10),
        "reference_number": "REF-A",
        "job_posting_url": "https://example.com/a",
        "notes": 'Has, comma and "quotes"',
    }, files={
        "resume_pdf": _pdf("my-resume-final.pdf", b"RESUME"),
        "application_pdf": _pdf("app-copy (2).pdf", b"APP"),
    }, follow_redirects=False)
    a1_id = int(a1.headers["location"].rsplit("/", 1)[1])

    a2 = client.post("/applications/new", data={
        "company": "Acme Corp",
        "job_title": "SRE",
        "applied_on": at(30),
        "reference_number": "REF-D",
    }, follow_redirects=False)
    a2_id = int(a2.headers["location"].rsplit("/", 1)[1])

    b1 = client.post("/applications/new", data={
        "company": "Globex",
        "job_title": "Data Analyst",
        "applied_on": at(4),
    }, files={"application_pdf": _pdf("cover-letter.pdf", b"COVER")},
        follow_redirects=False)
    b1_id = int(b1.headers["location"].rsplit("/", 1)[1])

    client.post("/applications/new", data={
        "company": "Initech",
        "job_title": "Frontend Dev",
        "applied_on": at(2),
        "reference_number": "REF-C",
    }, follow_redirects=False)

    # Status changes (each appends exactly one event row): A2 -> rejected,
    # B1 -> offer. Fields echo the created values so only status moves.
    client.post(f"/applications/{a2_id}/update", data={
        "company": "Acme Corp",
        "job_title": "SRE",
        "applied_on": at(30),
        "reference_number": "REF-D",
        "status": "rejected",
    }, follow_redirects=False)
    client.post(f"/applications/{b1_id}/update", data={
        "company": "Globex",
        "job_title": "Data Analyst",
        "applied_on": at(4),
        "status": "offer",
    }, follow_redirects=False)

    return R


def _parse_csv(text: str) -> list[list[str]]:
    """All CSV rows (header first) as lists of strings."""
    return [row for row in csv.reader(io.StringIO(text))]


def _app_row(app) -> list[str]:
    """One application serialized exactly the way the endpoint must (§5)."""
    return [
        str(app.id),
        app.company,
        app.job_title,
        app.reference_number or "",
        app.applied_on.isoformat(),
        app.status,
        app.job_posting_url or "",
        app.notes or "",
        app.resume_file_name or "",  # original filename as stored in S2
        app.application_file_name or "",  # original filename as stored in S2
        app.created_at.isoformat(),
        app.updated_at.isoformat(),
    ]


def _event_row(event, company: str) -> list[str]:
    """One status event serialized exactly the way the endpoint must (§5)."""
    return [
        str(event.application_id),
        company,
        event.from_status or "",  # initial creation has no previous status
        event.to_status,
        event.changed_at.isoformat(),
    ]


def _assert_download_filename(response, prefix: str) -> None:
    assert response.status_code == 200
    assert "text/csv" in response.headers["content-type"]
    disposition = response.headers["content-disposition"]
    pattern = rf'^attachment; filename="{prefix}_\d{{8}}_\d{{4}}\.csv"$'
    assert re.match(pattern, disposition), disposition


# ---------------------------------------------------------------------------
# applications export: full dataset and every filter combination (§5)
# ---------------------------------------------------------------------------

def test_full_export_columns_and_rows_match_db_exactly(client):
    _seed(client)
    response = client.get("/api/export.csv")
    _assert_download_filename(response, "applications")

    rows = _parse_csv(response.text)
    # Columns exactly per §5 — including the two original-filename columns.
    assert rows[0] == APP_COLUMNS

    with open_session() as session:
        apps = repo.list_applications(session)
    # Every row, in order, matches the database content exactly.
    assert len(rows) - 1 == len(apps) == 4
    assert rows[1:] == [_app_row(app) for app in apps]

    # Spot-checks on the tricky cells: CSV-hostile notes survive quoting and
    # the PDF columns carry the original filenames, not the storage paths.
    a1 = next(app for app in apps if app.resume_file_name)
    row = rows[1 + [app.id for app in apps].index(a1.id)]
    assert row[7] == 'Has, comma and "quotes"'
    assert row[8] == "my-resume-final.pdf"
    assert row[9] == "app-copy (2).pdf"


def test_single_company_filter_matches_same_predicate(client):
    _seed(client)
    response = client.get("/api/export.csv", params={"company": "Acme Corp"})

    rows = _parse_csv(response.text)
    with open_session() as session:
        expected = repo.list_applications(session, company="Acme Corp")
    assert rows[1:] == [_app_row(app) for app in expected]
    # A1 (R-10) sorts before A2 (R-30); Globex/Initech are absent.
    assert [row[1] for row in rows[1:]] == ["Acme Corp", "Acme Corp"]


def test_status_subset_filter_matches_same_predicate(client):
    _seed(client)
    response = client.get(
        "/api/export.csv", params={"status": ["received", "offer"]}
    )

    rows = _parse_csv(response.text)
    with open_session() as session:
        expected = repo.list_applications(session, statuses=["received", "offer"])
    assert rows[1:] == [_app_row(app) for app in expected]
    # Newest first: C1 (R-2, received), B1 (R-4, offer), A1 (R-10, still
    # received); the rejected application is gone.
    assert [row[5] for row in rows[1:]] == ["received", "offer", "received"]


def test_date_range_filter_matches_same_predicate(client):
    R = _seed(client)
    date_from = (R - timedelta(days=4)).isoformat()  # inclusive lower bound
    response = client.get("/api/export.csv", params={"date_from": date_from})

    rows = _parse_csv(response.text)
    with open_session() as session:
        expected = repo.list_applications(session, date_from=R - timedelta(days=4))
    assert rows[1:] == [_app_row(app) for app in expected]
    # C1 (R-2) sorts first; B1 sits exactly on the from-date boundary and is
    # included.
    assert [row[4] for row in rows[1:]] == [(R - timedelta(days=2)).isoformat(), date_from]


def test_unmatched_filter_exports_header_only(client):
    _seed(client)
    response = client.get("/api/export.csv", params={"company": "NoSuchCorp"})
    _assert_download_filename(response, "applications")

    rows = _parse_csv(response.text)
    assert rows == [APP_COLUMNS]


def test_both_endpoints_produce_correctly_named_downloads(client):
    _seed(client)
    _assert_download_filename(client.get("/api/export.csv"), "applications")
    _assert_download_filename(client.get("/api/events.csv"), "status_events")


# ---------------------------------------------------------------------------
# events export: full status histories, in order, with company joined (§5)
# ---------------------------------------------------------------------------

def test_events_full_history_matches_repo_order_with_company_join(client):
    _seed(client)
    response = client.get("/api/events.csv")
    _assert_download_filename(response, "status_events")

    rows = _parse_csv(response.text)
    assert rows[0] == EVENT_COLUMNS

    with open_session() as session:
        events = repo.get_status_events_for_filter(session)
        companies = {app.id: app.company for app in repo.list_applications(session)}
    # One row per event — initial creation included (empty from_status) — in
    # exactly the repository's deterministic order, company names joined.
    assert rows[1:] == [_event_row(event, companies[event.application_id]) for event in events]

    # 4 applications, two of them changed once: 6 events total; each app's
    # first row is its creation with an empty from_status.
    assert len(events) == 6
    by_app: dict[str, list[list[str]]] = {}
    for row in rows[1:]:
        by_app.setdefault(row[0], []).append(row)
    for app_id, app_rows in by_app.items():
        assert app_rows[0][2] == "" and app_rows[0][3] == "received"


def test_events_company_filter_matches_same_predicate(client):
    _seed(client)
    response = client.get("/api/events.csv", params={"company": "Acme Corp"})

    rows = _parse_csv(response.text)
    with open_session() as session:
        events = repo.get_status_events_for_filter(session, company="Acme Corp")
        companies = {
            app.id: app.company
            for app in repo.list_applications(session, company="Acme Corp")
        }
    assert rows[1:] == [_event_row(event, companies[event.application_id]) for event in events]
    # A2's full two-event history plus A1's single creation — Globex absent.
    assert [row[1] for row in rows[1:]] == ["Acme Corp"] * 3


# ---------------------------------------------------------------------------
# header wiring: export links carry the active filter query string (§6 item 1)
# ---------------------------------------------------------------------------

def test_header_export_links_carry_active_filter(client):
    _seed(client)

    page = client.get("/").text
    assert 'href="/api/export.csv"' in page
    assert 'href="/api/events.csv"' in page

    filtered = client.get("/?company=Acme%20Corp&status=interviewing").text
    query = "company=Acme+Corp&amp;status=interviewing"  # &amp;: HTML-escaped
    assert f'href="/api/export.csv?{query}"' in filtered
    assert f'href="/api/events.csv?{query}"' in filtered
