"""HTTP/API-level tests for the application routes and PDF uploads.

Everything runs offline through FastAPI's TestClient against a throwaway
database under pytest's ``tmp_path``; uploaded "PDFs" are generated byte
strings, never real files. The live DATA_DIR is never touched.
"""

from datetime import date, datetime, time as dt_time, timedelta
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app import config, db, repo, uploads
from app.db import open_session
from app.main import create_app
from app.models import utc_now


@pytest.fixture()
def client(tmp_path, monkeypatch):
    """An app wired to a fresh temp DATA_DIR (database + upload files)."""
    data_dir = tmp_path / "data"
    # config reads it at call time for uploads; db binds its own copy and the
    # lazily-created engine/session factory must be dropped so lifespan's
    # init_db() rebuilds them against this test's temp dir.
    monkeypatch.setattr(config, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "_default_engine", None)
    monkeypatch.setattr(db, "_default_factory", None)

    with TestClient(create_app()) as test_client:
        yield test_client

    # Don't let later tests (e.g. repo-level ones using their own engines) or
    # a re-imported module reuse this test's temp database.
    db._default_engine = None
    db._default_factory = None


@pytest.fixture()
def data_dir(tmp_path):
    """The on-disk root the client fixture pointed DATA_DIR at."""
    return tmp_path / "data"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _pdf(name: str, tag: bytes) -> tuple[str, bytes, str]:
    """A generated PDF-shaped payload for multipart uploads."""
    return name, b"%PDF-1.7\n% " + tag + b"\n%%EOF", "application/pdf"


def _create(client, files=None, **fields):
    payload = {
        "company": "Acme Corp",
        "job_title": "Backend Engineer",
        "applied_on": "2026-10-01",
        **(dict(fields) if fields else {}),
    }
    return client.post(
        "/applications/new", data=payload, files=files or [], follow_redirects=False
    )


def _update(client, application_id, files=None, **fields):
    payload = {
        "company": "Acme Corp",
        "job_title": "Backend Engineer",
        "applied_on": "2026-10-01",
        "status": "received",
        **(dict(fields) if fields else {}),
    }
    return client.post(
        f"/applications/{application_id}/update",
        data=payload,
        files=files or [],
        follow_redirects=False,
    )


def _created_id(response) -> int:
    assert response.status_code == 303, response.text
    return int(response.headers["location"].rsplit("/", 1)[1])


def events_for(application_id):
    """The full status_event chain for one application, as (from, to) pairs."""
    with open_session() as session:
        return [(e.from_status, e.to_status) for e in repo.get_status_events(session, application_id)]


# ---------------------------------------------------------------------------
# create + detail page
# ---------------------------------------------------------------------------

def test_create_redirects_to_detail_and_starts_received(client):
    response = _create(client)
    application_id = _created_id(response)
    assert response.headers["location"] == f"/applications/{application_id}"

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row is not None and row.status == "received"
    # creation writes exactly one initial status event
    assert events_for(application_id) == [(None, "received")]

    page = client.get(f"/applications/{application_id}")
    assert page.status_code == 200
    for text in ("Acme Corp", "Backend Engineer", "received"):
        assert text in page.text


def test_create_with_recorded_history_writes_full_chain(client):
    response = _create(
        client,
        applied_on="2026-09-01",
        history_status=["interviewing", "accepted"],
        history_date=["2026-09-05", "2026-09-12"],
    )
    application_id = _created_id(response)

    with open_session() as session:
        row = repo.get_application(session, application_id)
        chain = [
            (e.from_status, e.to_status, e.changed_at.date())
            for e in repo.get_status_events(session, application_id)
        ]
    assert row.status == "accepted"  # final step wins
    assert chain == [
        (None, "received", date(2026, 9, 1)),
        ("received", "interviewing", date(2026, 9, 5)),
        ("interviewing", "accepted", date(2026, 9, 12)),
    ]


def test_create_with_malformed_history_renders_error_and_creates_nothing(client):
    # A step with a status but no date is rejected before anything is written.
    response = _create(client, history_status=["interviewing"], history_date=[""])
    assert response.status_code == 200
    assert "needs both a status and a date" in response.text
    home = client.get("/")
    assert "No applications yet" in home.text


def test_fix_miskeyed_rejection_date_in_place(client):
    """The reported bug: a wrong rejection date used to force delete + recreate."""
    response = _create(
        client,
        applied_on="2026-09-01",
        history_status=["interviewing", "rejected"],
        history_date=["2026-09-05", "2026-09-20"],
    )
    application_id = _created_id(response)

    with open_session() as session:
        rejected_step = next(
            e for e in repo.get_status_events(session, application_id) if e.to_status == "rejected"
        )
        step_id = rejected_step.id

    fix = client.post(
        f"/applications/{application_id}/events/{step_id}",
        data={"changed_on": "2026-09-25"},
        follow_redirects=False,
    )
    assert fix.status_code == 303

    with open_session() as session:
        chain = [
            (e.from_status, e.to_status, e.changed_at.date())
            for e in repo.get_status_events(session, application_id)
        ]
        row = repo.get_application(session, application_id)
    # No extra step was appended; the existing one moved.
    assert [c[1] for c in chain] == ["received", "interviewing", "rejected"]
    assert chain[-1][2] == date(2026, 9, 25)
    assert row.status == "rejected"


def test_timeline_edit_rejects_first_step_status_change(client):
    response = _create(client, applied_on="2026-09-01")
    application_id = _created_id(response)
    with open_session() as session:
        (first,) = repo.get_status_events(session, application_id)
        first_id = first.id

    bad = client.post(
        f"/applications/{application_id}/events/{first_id}",
        data={"new_status": "interviewing"},
    )
    assert bad.status_code == 200
    # (quotes are HTML-escaped in the rendered page)
    assert "the first step always stays" in bad.text


def test_timeline_rendered_with_inline_edit_forms(client):
    response = _create(
        client,
        applied_on="2026-09-01",
        history_status=["interviewing", "rejected"],
        history_date=["2026-09-05", "2026-09-20"],
    )
    application_id = _created_id(response)

    page = client.get(f"/applications/{application_id}").text
    # One edit form per recorded step (three here), the first without a status select.
    assert page.count('class="event-edit"') == 3
    assert 'name="changed_on"' in page
    assert page.count("name=\"new_status\"") == 2  # only non-initial steps


def test_index_lists_all_applications(client):
    home = client.get("/")
    assert home.status_code == 200
    # empty state before anything exists
    assert "No applications yet" in home.text

    _create(client, job_title="Platform Engineer")
    home = client.get("/")
    assert "Acme Corp" in home.text and "Platform Engineer" in home.text


def test_tampered_status_on_create_is_ignored(client):
    # The create form has no status field; a tampered one must not stick.
    _create(client, **{"status": "offer"})

    with open_session() as session:
        rows = repo.list_applications(session)
    assert len(rows) == 1 and rows[0].status == "received"


def test_create_validation_errors_rerender_with_values_preserved(client):
    response = _create(client, company="", job_title="Test Engineer", applied_on="not-a-date")

    assert response.status_code == 200  # re-rendered form, not a redirect
    for message in ("Company is required.", "is not a valid date"):
        assert message in response.text
    # the user's input comes back on the form for a retry
    assert 'value="Test Engineer"' in response.text

    with open_session() as session:
        assert repo.list_applications(session) == []  # nothing was persisted


def test_create_with_both_pdfs_stores_bytes_and_metadata(client, data_dir):
    resume = _pdf("my-cv.pdf", b"resume-bytes")
    application_pdf = _pdf("cover-letter.pdf", b"application-bytes")
    response = _create(
        client, files=[("resume_pdf", resume), ("application_pdf", application_pdf)]
    )
    application_id = _created_id(response)

    # exact bytes land under the stable per-application paths
    root = data_dir / "uploads" / str(application_id)
    assert (root / "resume.pdf").read_bytes() == resume[1]
    assert (root / "application.pdf").read_bytes() == application_pdf[1]

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "my-cv.pdf"
    assert row.application_file_name == "cover-letter.pdf"
    # the database keeps DATA_DIR-relative paths; original names stay metadata-only
    assert row.resume_pdf == f"uploads/{application_id}/resume.pdf"
    assert row.application_pdf == f"uploads/{application_id}/application.pdf"

    page = client.get(f"/applications/{application_id}")
    assert "my-cv.pdf" in page.text and "cover-letter.pdf" in page.text


# ---------------------------------------------------------------------------
# upload validation
# ---------------------------------------------------------------------------

def test_upload_rejects_content_that_is_not_a_pdf(client, data_dir):
    fake = ("x.pdf", b"this is not a pdf at all", "application/pdf")
    response = _create(client, files=[("resume_pdf", fake)])

    assert response.status_code == 200
    assert "does not look like a valid PDF file" in response.text
    # rejected before anything was written: no row, no disk state
    with open_session() as session:
        assert repo.list_applications(session) == []
    assert not (data_dir / "uploads").exists()


def test_upload_rejects_non_pdf_extension(client, data_dir):
    docx = ("cv.docx", b"%PDF-1.7\n% real pdf bytes", "application/pdf")
    response = _create(client, files=[("resume_pdf", docx)])

    assert response.status_code == 200
    assert ".pdf extension" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []
    assert not (data_dir / "uploads").exists()


def test_upload_rejects_oversized_file_before_disk_write(client, data_dir):
    cap = uploads.max_upload_bytes()
    oversized = ("huge.pdf", b"%PDF-1.7\n" + b"\x00" * cap, "application/pdf")
    assert len(oversized[1]) > cap

    response = _create(client, files=[("resume_pdf", oversized)])

    assert response.status_code == 200
    assert "upload limit" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []
    # size is checked before any write — nothing may exist on disk at all
    assert not (data_dir / "uploads").exists()


def test_create_disk_failure_cleans_up_row_and_files(client, data_dir, monkeypatch):
    def exploding_store(**kwargs):
        raise OSError("disk full")

    monkeypatch.setattr(uploads, "store_upload", exploding_store)

    response = _create(client, files=[("resume_pdf", _pdf("cv.pdf", b"lost"))])

    assert response.status_code == 200
    assert "Could not save the uploaded file" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []  # half-created row rolled back
    uploads_root = data_dir / "uploads"
    assert not uploads_root.exists() or list(uploads_root.glob("*")) == []


# ---------------------------------------------------------------------------
# updates
# ---------------------------------------------------------------------------

def test_update_status_appends_event_and_redirects(client):
    application_id = _created_id(_create(client))

    response = _update(client, application_id, status="interviewing")
    assert response.status_code == 303
    assert events_for(application_id) == [(None, "received"), ("received", "interviewing")]

    page = client.get(f"/applications/{application_id}")
    assert "interviewing" in page.text


def test_update_replaces_pdf_and_updates_metadata(client, data_dir):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("cv-v1.pdf", b"old-bytes"))])
    )

    response = _update(
        client,
        application_id,
        status="interviewing",
        files=[("resume_pdf", _pdf("cv-v2.pdf", b"new-bytes"))],
    )
    assert response.status_code == 303

    # the file was replaced in place at its stable path
    stored = data_dir / "uploads" / str(application_id) / "resume.pdf"
    assert stored.read_bytes() == b"%PDF-1.7\n% new-bytes\n%%EOF"

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "cv-v2.pdf"  # metadata follows the replacement

    download = client.get(f"/files/{application_id}/resume")
    assert download.status_code == 200
    assert download.content == b"%PDF-1.7\n% new-bytes\n%%EOF"
    assert 'filename="cv-v2.pdf"' in download.headers["content-disposition"]


def test_update_without_file_keeps_existing_pdf_and_events(client, data_dir):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("cv.pdf", b"kept-bytes"))])
    )

    response = _update(client, application_id, notes="only a note edit")
    assert response.status_code == 303

    stored = data_dir / "uploads" / str(application_id) / "resume.pdf"
    assert stored.read_bytes() == b"%PDF-1.7\n% kept-bytes\n%%EOF"
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "cv.pdf" and row.notes == "only a note edit"
    # no status change -> no new event; the initial one is still all we have
    assert events_for(application_id) == [(None, "received")]


def test_update_inline_errors_preserve_values_and_commit_nothing(client):
    application_id = _created_id(_create(client))

    response = _update(
        client,
        application_id,
        company="Renamed Corp",  # valid field that must NOT stick on failure
        status="bogus-status",
    )

    assert response.status_code == 200
    assert "must be one of" in response.text
    # the submitted values are echoed back for a retry
    assert 'value="Renamed Corp"' in response.text
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.company == "Acme Corp"  # nothing was written on validation failure
    assert events_for(application_id) == [(None, "received")]


# ---------------------------------------------------------------------------
# automatic ghosting on dashboard load
# ---------------------------------------------------------------------------

def test_index_route_ghosts_stale_received_rows(client):
    application_id = _created_id(_create(client))
    # Backdate this row past the inactivity window, directly.
    with open_session() as session:
        row = repo.get_application(session, application_id)
        stale = datetime.combine(
            utc_now().date()
            - timedelta(days=config.GHOST_AFTER_DAYS + 1),
            dt_time.min,
        )
        row.updated_at = stale
        session.commit()

    page = client.get("/")  # loading the dashboard runs the sweep
    assert page.status_code == 200

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.status == "ghosted"
    events = _events_with_times(application_id)
    pairs = [(e.from_status, e.to_status) for e in events]
    assert ("received", "ghosted") in pairs
    ghost_event = next(e for e in events if e.to_status == "ghosted")
    # the sweep stamps now, not the stale day
    assert ghost_event.changed_at > stale


# ---------------------------------------------------------------------------
# delete + 404s
# ---------------------------------------------------------------------------

def test_delete_removes_row_events_and_files(client, data_dir):
    application_id = _created_id(
        _create(
            client,
            files=[("resume_pdf", _pdf("cv.pdf", b"gone-soon")), ("application_pdf", _pdf("app.pdf", b"gone-too"))],
        )
    )
    _update(client, application_id, status="interviewing")  # two events now

    response = client.post(f"/applications/{application_id}/delete", follow_redirects=False)
    assert response.status_code == 303
    assert response.headers["location"] == "/"

    with open_session() as session:
        assert repo.get_application(session, application_id) is None
    assert events_for(application_id) == []
    # both stored PDFs and their directory are gone
    assert not (data_dir / "uploads" / str(application_id)).exists()


def test_unknown_application_ids_404(client):
    assert client.get("/applications/999").status_code == 404
    assert _update(client, 999).status_code == 404
    assert client.post("/applications/999/delete", follow_redirects=False).status_code == 404


# ---------------------------------------------------------------------------
# manual status-change date (backdated events)
# ---------------------------------------------------------------------------

def _events_with_times(application_id):
    """The full event history with timestamps, oldest first."""
    with open_session() as session:
        return list(repo.get_status_events(session, application_id))


def test_update_backdates_the_appended_event(client):
    application_id = _created_id(_create(client))

    response = _update(
        client,
        application_id,
        status="interviewing",
        status_changed_on="2026-07-01",
    )
    assert response.status_code == 303

    events = _events_with_times(application_id)
    assert len(events) == 2
    # The backdated event legitimately sorts ahead of the creation-time one.
    changed = next(e for e in events if e.to_status == "interviewing")
    assert (changed.from_status, changed.to_status) == ("received", "interviewing")
    # The given calendar day becomes midnight UTC on that date.
    assert changed.changed_at.date() == date(2026, 7, 1)
    assert changed.changed_at.time().isoformat() == "00:00:00"


def test_update_blank_status_date_stamps_today(client):
    application_id = _created_id(_create(client))

    response = _update(client, application_id, status="rejected")
    assert response.status_code == 303

    events = _events_with_times(application_id)
    changed = next(e for e in events if e.to_status == "rejected")
    assert changed.changed_at.date() == utc_now().date()


def test_update_future_status_date_is_rejected_and_writes_nothing(client):
    application_id = _created_id(_create(client))
    tomorrow = (utc_now().date() + timedelta(days=1)).isoformat()

    response = _update(
        client,
        application_id,
        status="interviewing",
        status_changed_on=tomorrow,
    )
    assert response.status_code == 200  # re-rendered form, not a redirect
    assert "cannot be in the future" in response.text
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.status == "received"
    assert events_for(application_id) == [(None, "received")]


def test_update_invalid_status_date_is_rejected_and_writes_nothing(client):
    application_id = _created_id(_create(client))

    response = _update(
        client,
        application_id,
        status="interviewing",
        status_changed_on="not-a-date",
    )
    assert response.status_code == 200
    assert "is not a valid date" in response.text
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.status == "received"
    assert events_for(application_id) == [(None, "received")]


def test_same_status_with_backdate_appends_no_event(client):
    application_id = _created_id(_create(client))

    response = _update(
        client,
        application_id,
        status="received",  # same as current → no transition, date ignored
        status_changed_on="2026-07-01",
    )
    assert response.status_code == 303
    assert events_for(application_id) == [(None, "received")]


# ---------------------------------------------------------------------------
# file downloads
# ---------------------------------------------------------------------------

def test_download_serves_stored_pdf_with_original_name(client):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("final-cv.pdf", b"download-bytes"))])
    )

    response = client.get(f"/files/{application_id}/resume")
    assert response.status_code == 200
    assert response.headers["content-type"] == "application/pdf"
    # original upload name, not the stable storage path
    assert 'filename="final-cv.pdf"' in response.headers["content-disposition"]
    assert response.content == b"%PDF-1.7\n% download-bytes\n%%EOF"


def test_download_404_for_missing_file_kind_app_or_deleted_on_disk(client, data_dir):
    # an application with no uploads at all
    bare_id = _created_id(_create(client))
    assert client.get(f"/files/{bare_id}/resume").status_code == 404
    assert client.get(f"/files/{bare_id}/application").status_code == 404

    # unknown application id and unknown kind
    assert client.get("/files/999/resume").status_code == 404
    assert client.get(f"/files/{bare_id}/bogus").status_code == 404

    # file present in the database but missing on disk (e.g. manually deleted)
    uploaded_id = _created_id(_create(client, files=[("resume_pdf", _pdf("cv.pdf", b"x"))]))
    stored = data_dir / "uploads" / str(uploaded_id) / "resume.pdf"
    stored.unlink()
    assert client.get(f"/files/{uploaded_id}/resume").status_code == 404
