"""HTTP/API-level tests for the application routes and PDF uploads (PLAN.md §5).

Everything runs offline through FastAPI's TestClient against a throwaway
database under pytest's ``tmp_path``; uploaded "PDFs" are generated byte
strings, never real files. The live DATA_DIR is never touched (§7).
"""

from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app import config, db, repo, uploads
from app.db import open_session
from app.main import create_app


@pytest.fixture()
def client(tmp_path, monkeypatch):
    """An app wired to a fresh temp DATA_DIR (database + upload files)."""
    data_dir = tmp_path / "data"
    # config reads it at call time for uploads; db binds its own copy and the
    # lazily-created engine/session factory must be dropped so lifespan's
    # init_db() rebuilds them against this test's temp dir.
    monkeypatch.setattr(config, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "DATA_DIR", str(data_dir))
    monkeypatch.setattr(db, "_default_engine", None)
    monkeypatch.setattr(db, "_default_factory", None)

    with TestClient(create_app()) as test_client:
        yield test_client

    # Don't let later tests (e.g. repo-level ones using their own engines) or
    # a re-imported module reuse this test's temp database.
    db._default_engine = None
    db._default_factory = None


@pytest.fixture()
def data_dir(tmp_path):
    """The on-disk root the client fixture pointed DATA_DIR at."""
    return tmp_path / "data"


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def _pdf(name: str, tag: bytes) -> tuple[str, bytes, str]:
    """A generated PDF-shaped payload for multipart uploads (offline §7)."""
    return name, b"%PDF-1.7\n% " + tag + b"\n%%EOF", "application/pdf"


def _create(client, files=None, **fields):
    payload = {
        "company": "Acme Corp",
        "job_title": "Backend Engineer",
        "applied_on": "2026-10-01",
        **(dict(fields) if fields else {}),
    }
    return client.post(
        "/applications/new", data=payload, files=files or [], follow_redirects=False
    )


def _update(client, application_id, files=None, **fields):
    payload = {
        "company": "Acme Corp",
        "job_title": "Backend Engineer",
        "applied_on": "2026-10-01",
        "status": "received",
        **(dict(fields) if fields else {}),
    }
    return client.post(
        f"/applications/{application_id}/update",
        data=payload,
        files=files or [],
        follow_redirects=False,
    )


def _created_id(response) -> int:
    assert response.status_code == 303, response.text
    return int(response.headers["location"].rsplit("/", 1)[1])


def events_for(application_id):
    """The full status_event chain for one application, as (from, to) pairs."""
    with open_session() as session:
        return [(e.from_status, e.to_status) for e in repo.get_status_events(session, application_id)]


# ---------------------------------------------------------------------------
# create + detail page (§5)
# ---------------------------------------------------------------------------

def test_create_redirects_to_detail_and_starts_received(client):
    response = _create(client)
    application_id = _created_id(response)
    assert response.headers["location"] == f"/applications/{application_id}"

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row is not None and row.status == "received"
    # creation writes exactly one initial status event (§4)
    assert events_for(application_id) == [(None, "received")]

    page = client.get(f"/applications/{application_id}")
    assert page.status_code == 200
    for text in ("Acme Corp", "Backend Engineer", "received"):
        assert text in page.text


def test_index_placeholder_lists_applications(client):
    home = client.get("/")
    assert home.status_code == 200
    # S3 builds the real dashboard; this is only a placeholder (§5/§6)
    assert "No applications yet" in home.text

    _create(client, job_title="Platform Engineer")
    home = client.get("/")
    assert "Acme Corp" in home.text and "Platform Engineer" in home.text


def test_tampered_status_on_create_is_ignored(client):
    # The create form has no status field; a tampered one must not stick (§4).
    _create(client, **{"status": "offer"})

    with open_session() as session:
        rows = repo.list_applications(session)
    assert len(rows) == 1 and rows[0].status == "received"


def test_create_validation_errors_rerender_with_values_preserved(client):
    response = _create(client, company="", job_title="Test Engineer", applied_on="not-a-date")

    assert response.status_code == 200  # re-rendered form, not a redirect
    for message in ("Company is required.", "is not a valid date"):
        assert message in response.text
    # the user's input comes back on the form (§5 inline errors)
    assert 'value="Test Engineer"' in response.text

    with open_session() as session:
        assert repo.list_applications(session) == []  # nothing was persisted


def test_create_with_both_pdfs_stores_bytes_and_metadata(client, data_dir):
    resume = _pdf("my-cv.pdf", b"resume-bytes")
    application_pdf = _pdf("cover-letter.pdf", b"application-bytes")
    response = _create(
        client, files=[("resume_pdf", resume), ("application_pdf", application_pdf)]
    )
    application_id = _created_id(response)

    # exact bytes land under the stable per-application paths (§7)
    root = data_dir / "uploads" / str(application_id)
    assert (root / "resume.pdf").read_bytes() == resume[1]
    assert (root / "application.pdf").read_bytes() == application_pdf[1]

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "my-cv.pdf"
    assert row.application_file_name == "cover-letter.pdf"
    # the database keeps DATA_DIR-relative paths; original names stay metadata-only
    assert row.resume_pdf == f"uploads/{application_id}/resume.pdf"
    assert row.application_pdf == f"uploads/{application_id}/application.pdf"

    page = client.get(f"/applications/{application_id}")
    assert "my-cv.pdf" in page.text and "cover-letter.pdf" in page.text


# ---------------------------------------------------------------------------
# upload validation (§7)
# ---------------------------------------------------------------------------

def test_upload_rejects_content_that_is_not_a_pdf(client, data_dir):
    fake = ("x.pdf", b"this is not a pdf at all", "application/pdf")
    response = _create(client, files=[("resume_pdf", fake)])

    assert response.status_code == 200
    assert "does not look like a valid PDF file" in response.text
    # rejected before anything was written: no row, no disk state
    with open_session() as session:
        assert repo.list_applications(session) == []
    assert not (data_dir / "uploads").exists()


def test_upload_rejects_non_pdf_extension(client, data_dir):
    docx = ("cv.docx", b"%PDF-1.7\n% real pdf bytes", "application/pdf")
    response = _create(client, files=[("resume_pdf", docx)])

    assert response.status_code == 200
    assert ".pdf extension" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []
    assert not (data_dir / "uploads").exists()


def test_upload_rejects_oversized_file_before_disk_write(client, data_dir):
    cap = uploads.max_upload_bytes()
    oversized = ("huge.pdf", b"%PDF-1.7\n" + b"\x00" * cap, "application/pdf")
    assert len(oversized[1]) > cap

    response = _create(client, files=[("resume_pdf", oversized)])

    assert response.status_code == 200
    assert "upload limit" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []
    # size is checked before any write — nothing may exist on disk at all
    assert not (data_dir / "uploads").exists()


def test_create_disk_failure_cleans_up_row_and_files(client, data_dir, monkeypatch):
    def exploding_store(**kwargs):
        raise OSError("disk full")

    monkeypatch.setattr(uploads, "store_upload", exploding_store)

    response = _create(client, files=[("resume_pdf", _pdf("cv.pdf", b"lost"))])

    assert response.status_code == 200
    assert "Could not save the uploaded file" in response.text
    with open_session() as session:
        assert repo.list_applications(session) == []  # half-created row rolled back
    uploads_root = data_dir / "uploads"
    assert not uploads_root.exists() or list(uploads_root.glob("*")) == []


# ---------------------------------------------------------------------------
# updates (§5/§7)
# ---------------------------------------------------------------------------

def test_update_status_appends_event_and_redirects(client):
    application_id = _created_id(_create(client))

    response = _update(client, application_id, status="interviewing")
    assert response.status_code == 303
    assert events_for(application_id) == [(None, "received"), ("received", "interviewing")]

    page = client.get(f"/applications/{application_id}")
    assert "interviewing" in page.text


def test_update_replaces_pdf_and_updates_metadata(client, data_dir):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("cv-v1.pdf", b"old-bytes"))])
    )

    response = _update(
        client,
        application_id,
        status="interviewing",
        files=[("resume_pdf", _pdf("cv-v2.pdf", b"new-bytes"))],
    )
    assert response.status_code == 303

    # the file was replaced in place at its stable path (§7)
    stored = data_dir / "uploads" / str(application_id) / "resume.pdf"
    assert stored.read_bytes() == b"%PDF-1.7\n% new-bytes\n%%EOF"

    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "cv-v2.pdf"  # metadata follows the replacement

    download = client.get(f"/files/{application_id}/resume")
    assert download.status_code == 200
    assert download.content == b"%PDF-1.7\n% new-bytes\n%%EOF"
    assert 'filename="cv-v2.pdf"' in download.headers["content-disposition"]


def test_update_without_file_keeps_existing_pdf_and_events(client, data_dir):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("cv.pdf", b"kept-bytes"))])
    )

    response = _update(client, application_id, notes="only a note edit")
    assert response.status_code == 303

    stored = data_dir / "uploads" / str(application_id) / "resume.pdf"
    assert stored.read_bytes() == b"%PDF-1.7\n% kept-bytes\n%%EOF"
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.resume_file_name == "cv.pdf" and row.notes == "only a note edit"
    # no status change -> no new event (§4); the initial one is still all we have
    assert events_for(application_id) == [(None, "received")]


def test_update_inline_errors_preserve_values_and_commit_nothing(client):
    application_id = _created_id(_create(client))

    response = _update(
        client,
        application_id,
        company="Renamed Corp",  # valid field that must NOT stick on failure
        status="bogus-status",
    )

    assert response.status_code == 200
    assert "must be one of" in response.text
    # the submitted values are echoed back for a retry (§5)
    assert 'value="Renamed Corp"' in response.text
    with open_session() as session:
        row = repo.get_application(session, application_id)
    assert row.company == "Acme Corp"  # nothing was written on validation failure
    assert events_for(application_id) == [(None, "received")]


# ---------------------------------------------------------------------------
# delete + 404s (§5)
# ---------------------------------------------------------------------------

def test_delete_removes_row_events_and_files(client, data_dir):
    application_id = _created_id(
        _create(
            client,
            files=[("resume_pdf", _pdf("cv.pdf", b"gone-soon")), ("application_pdf", _pdf("app.pdf", b"gone-too"))],
        )
    )
    _update(client, application_id, status="interviewing")  # two events now

    response = client.post(f"/applications/{application_id}/delete", follow_redirects=False)
    assert response.status_code == 303
    assert response.headers["location"] == "/"

    with open_session() as session:
        assert repo.get_application(session, application_id) is None
    assert events_for(application_id) == []
    # both stored PDFs and their directory are gone (§7)
    assert not (data_dir / "uploads" / str(application_id)).exists()


def test_unknown_application_ids_404(client):
    assert client.get("/applications/999").status_code == 404
    assert _update(client, 999).status_code == 404
    assert client.post("/applications/999/delete", follow_redirects=False).status_code == 404


# ---------------------------------------------------------------------------
# file downloads (§5/§7)
# ---------------------------------------------------------------------------

def test_download_serves_stored_pdf_with_original_name(client):
    application_id = _created_id(
        _create(client, files=[("resume_pdf", _pdf("final-cv.pdf", b"download-bytes"))])
    )

    response = client.get(f"/files/{application_id}/resume")
    assert response.status_code == 200
    assert response.headers["content-type"] == "application/pdf"
    # original upload name, not the stable storage path (§7)
    assert 'filename="final-cv.pdf"' in response.headers["content-disposition"]
    assert response.content == b"%PDF-1.7\n% download-bytes\n%%EOF"


def test_download_404_for_missing_file_kind_app_or_deleted_on_disk(client, data_dir):
    # an application with no uploads at all
    bare_id = _created_id(_create(client))
    assert client.get(f"/files/{bare_id}/resume").status_code == 404
    assert client.get(f"/files/{bare_id}/application").status_code == 404

    # unknown application id and unknown kind
    assert client.get("/files/999/resume").status_code == 404
    assert client.get(f"/files/{bare_id}/bogus").status_code == 404

    # file present in the database but missing on disk (e.g. manually deleted)
    uploaded_id = _created_id(_create(client, files=[("resume_pdf", _pdf("cv.pdf", b"x"))]))
    stored = data_dir / "uploads" / str(uploaded_id) / "resume.pdf"
    stored.unlink()
    assert client.get(f"/files/{uploaded_id}/resume").status_code == 404
